services:
  db:
    container_name: odoo-db-dev
    image: postgres:16
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    container_name: odoo-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "5678:5678"  # debugpy port
    volumes:
      - odoo-filestore:/var/lib/odoo
      - ../addons:/mnt/extra-addons
    restart: unless-stopped

volumes:
  odoo-db-data:
  odoo-filestore:
